vaadin-context-menu-addon/pom.xml
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/GridContextMenu.java

This project has been compiled with Java 8 and is not backwards compatible with earlier version. My fix uses java 6 for compilation and fixes the issues, that needed addressing.

Use Java 6 and fix missing final keywords

---

vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/ContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/GridContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/Menu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/MenuItem.java

Made ContextMenu and related classes serializable.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/21)

Fix #11: Made ContextMenu serializable

---

vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/ContextMenuConnector.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/24)

ignore command if the widget is no longer attached

---

vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/AbstractMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/ContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/GridContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/Menu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/MenuBar.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/MenuItem.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/MenuItemImpl.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/ContextMenuClientRpc.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/ContextMenuConnector.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/ContextMenuServerRpc.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/MenuSharedState.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/MyVMenuBar.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/MyVOverlay.java
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/VMenuItem.java
vaadin-context-menu-addon/src/test/java/com/vaadin/addon/contextmenu/ContextMenuTest.java
vaadin-context-menu-demo/src/main/java/com/vaadin/addon/contextmenu/ContextmenuUI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/32)

Format using Eclipse Neon and Vaadin settings

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/ContextMenuConnector.java
vaadin-context-menu-demo/pom.xml

Adapted from https://github.com/vaadin/context-menu/pull/30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/33)

Make compatible with Vaadin 7.7

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/client/ContextMenuConnector.java
vaadin-context-menu-demo/pom.xml

Closes #31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/34)

Fix compatibility with Vaadin 7.7.0

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-addon/src/main/java/com/vaadin/addon/contextmenu/MenuBar.java
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-demo/src/main/java/com/vaadin/addon/contextmenu/GridWithGenericListener.java
vaadin-context-menu-demo/src/main/java/com/vaadin/addon/contextmenu/GridWithGridListener.java
vaadin-context-menu-vaadin7-test/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/41)

Update to work with latest 8.0.0.alpha9

---

.travis.after_success.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/42)

Fix path to travis-settings.xml

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-demo/src/main/java/com/vaadin/addon/contextmenu/GridWithGenericListener.java
vaadin-context-menu-demo/src/main/java/com/vaadin/addon/contextmenu/GridWithGridListener.java
vaadin-context-menu-vaadin7-test/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/44)

Update to 8.0.0.beta1

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/45)

Update README to 2.0.0.beta1

---

pom.xml
vaadin-context-menu-addon/pom.xml
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-vaadin7-test/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/46)

Bump version to 2.0-SNAPSHOT

---

vaadin-context-menu-addon/pom.xml

adjust OSGi imports/exports (#39)
remove client side from OSGi import and export. See Issue #39 for more information
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/50)

adjust OSGi imports/exports (#39)

---

vaadin-context-menu-demo/pom.xml
vaadin-context-menu-demo/src/main/java/com/vaadin/contextmenu/ContextmenuUI.java

Depends on vaadin/framework#8208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/49)

Use Vaadin Icons (vaadin/framework#7979)

---

README.md

* Update README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/59)

Update README.md (#56)

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/ContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/v7/contextmenu/GridContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/v7/contextmenu/TableContextMenu.java
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-vaadin7-test/pom.xml
vaadin-context-menu-vaadin7-test/src/main/java/com/vaadin/v7/contextmenu/test/ContextMenuTreeTable.java
vaadin-context-menu-vaadin7-test/src/main/java/com/vaadin/v7/contextmenu/test/ContextmenuUI.java

Forward ported fix for #29 from 7.7 to a legacy TableContextMenu.
Updated to use 8.0.0.rc2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/61)

Fix Table and TreeTable with itemClickListener

---

vaadin-context-menu-vaadin7-test/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/62)

Get rid of vaadin-bom

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-vaadin7-test/pom.xml

Bumps vaadin version to 8.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/63)

Using vaadin 8.0.0

---

vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/GridContextMenu.java
vaadin-context-menu-demo/src/main/java/com/vaadin/contextmenu/GridWithGridListener.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/64)

Fix #55: Implemented Generics

---

vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/client/ContextMenuConnector.java
vaadin-context-menu-demo/src/main/java/com/vaadin/contextmenu/ContextmenuUI.java

Fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/87)

Don't open dummyRoot, if there is no items

---

vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/TreeContextMenu.java
vaadin-context-menu-demo/src/main/java/com/vaadin/contextmenu/ContextMenuUI.java

Fixes #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/92)

Support Tree context click

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/93)

Readme update for 3.0.0

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/98)

Remove the online demo as it is out-dated

---

vaadin-context-menu-addon/pom.xml
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-vaadin7-test/pom.xml

Related to vaadin/platform#766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/103)

Use https for Maven repositories

---

.travis.yml
vaadin-context-menu-addon/pom.xml
vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/ContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/GridContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/contextmenu/TreeContextMenu.java
vaadin-context-menu-addon/src/main/java/com/vaadin/v7/contextmenu/GridContextMenu.java
vaadin-context-menu-demo/pom.xml
vaadin-context-menu-vaadin7-test/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/context-menu/108)

Change to use SerializableEventListener
